In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'D:\Machine learning\ML Programs\NLP\Kindle review\all_kindle_review.csv')

In [3]:
df.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000


In [4]:
df = df[['reviewText','rating']]

In [14]:
df.head()

,reviewText,rating
0,"Jace Rankin may be short, but he's nothing to ...",3
1,Great short read. I didn't want to put it dow...,5
2,I'll start by saying this is the first of four...,3
3,Aggie is Angela Lansbury who carries pocketboo...,3
4,I did not expect this type of book to be in li...,4


In [16]:
df.shape

(12000, 2)

In [18]:
##missing values
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [20]:
df['rating'].unique()

array([3, 5, 4, 2, 1], dtype=int64)

In [22]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [ ]:
def change_review(value):
    if(value < 3):
        return 0
    else: return 1

In [24]:
##Preprocessing and Cleaning
df['rating'] = df['rating'].apply(lambda x:0 if x < 3 else 1) ##positive review is 1 and negative is 0

In [26]:
df.rating

0        1
1        1
2        1
3        1
4        1
        ..
11995    1
11996    1
11997    1
11998    0
11999    1
Name: rating, Length: 12000, dtype: int64

In [28]:
df.describe

<bound method NDFrame.describe of                                               reviewText  rating
0      Jace Rankin may be short, but he's nothing to ...       1
1      Great short read.  I didn't want to put it dow...       1
2      I'll start by saying this is the first of four...       1
3      Aggie is Angela Lansbury who carries pocketboo...       1
4      I did not expect this type of book to be in li...       1
...                                                  ...     ...
11995  Valentine cupid is a vampire- Jena and Ian ano...       1
11996  I have read all seven books in this series. Ap...       1
11997  This book really just wasn't my cuppa.  The si...       1
11998  tried to use it to charge my kindle, it didn't...       0
11999  Taking Instruction is a look into the often hi...       1

[12000 rows x 2 columns]>

In [30]:
df.rating.unique()

array([1, 0], dtype=int64)

In [32]:
df.rating.value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [34]:
##lower all the cases
df['reviewText'] = df['reviewText'].str.lower()

In [36]:
df.reviewText.head()

0    jace rankin may be short, but he's nothing to ...
1    great short read.  i didn't want to put it dow...
2    i'll start by saying this is the first of four...
3    aggie is angela lansbury who carries pocketboo...
4    i did not expect this type of book to be in li...
Name: reviewText, dtype: object

In [46]:
import re
from nltk.corpus import stopwords
from bs4 import BeautifulSoup
##removing special charaters
df['reviewText']=df['reviewText'].apply(lambda x:re.sub('[^a-z A-z 0-9-]+', '',x))
## Remove the stopswords
df['reviewText']=df['reviewText'].apply(lambda x:" ".join([y for y in x.split() if y not in stopwords.words('english')]))
## Remove url 
df['reviewText']=df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '' , str(x)))
## Remove html tags
df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())
## Remove any additional spaces
df['reviewText']=df['reviewText'].apply(lambda x: " ".join(x.split()))

C:\Users\ajayp\AppData\Local\Temp\ipykernel_11524\1142542079.py:11: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  df['reviewText']=df['reviewText'].apply(lambda x: BeautifulSoup(x, 'lxml').get_text())


In [48]:
df.head()

,reviewText,rating
0,jace rankin may short hes nothing mess man hau...,1
1,great short read didnt want put read one sitti...,1
2,ill start saying first four books wasnt expect...,1
3,aggie angela lansbury carries pocketbooks inst...,1
4,expect type book library pleased find price right,1


In [50]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [52]:
def lemmatize_word(text):
    return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [54]:
df['reviewText']=df['reviewText'].apply(lambda x: lemmatize_word(x))

In [56]:
df.head()

,reviewText,rating
0,jace rankin may short he nothing mess man haul...,1
1,great short read didnt want put read one sitti...,1
2,ill start saying first four book wasnt expecti...,1
3,aggie angela lansbury carry pocketbook instead...,1
4,expect type book library pleased find price right,1


In [58]:
##Train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df['reviewText'],df['rating'],test_size=0.2, random_state=42)

In [60]:
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer()

In [72]:
X_train_bow = bow.fit_transform(X_train).toarray()

In [76]:
X_test_bow = bow.transform(X_test).toarray()

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [78]:
X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()

In [80]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [84]:
from sklearn.naive_bayes import GaussianNB
nb_mobel_bow = GaussianNB().fit(X_train_bow, y_train)
nb_mobel_tfidf = GaussianNB().fit(X_train_tfidf, y_train)

In [86]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [88]:
y_pred_nbow = nb_mobel_bow.predict(X_test_bow)

In [90]:
y_pred_tfidf = nb_mobel_tfidf.predict(X_test_tfidf)

In [92]:
print("bow Accuracy =>",accuracy_score(y_test, y_pred_nbow))

bow Accuracy => 0.5745833333333333


In [94]:
print("tfidf Accuracy =>", accuracy_score(y_test, y_pred_tfidf))

tfidf Accuracy => 0.57875


In [98]:
print("Bow Confusion matrix :\n", confusion_matrix(y_test, y_pred_nbow))

Bow Confusion matrix :
 [[499 304]
 [717 880]]


In [102]:
print("tfidf Confusion matrix :\n", confusion_matrix(y_test, y_pred_tfidf))

tfidf Confusion matrix :
 [[488 315]
 [696 901]]


In [104]:
print("bow Classification report: \n", classification_report(y_test, y_pred_nbow))

bow Classification report: 
               precision    recall  f1-score   support

           0       0.41      0.62      0.49       803
           1       0.74      0.55      0.63      1597

    accuracy                           0.57      2400
   macro avg       0.58      0.59      0.56      2400
weighted avg       0.63      0.57      0.59      2400



In [106]:
print("tfidf Classification report: \n", classification_report(y_test, y_pred_tfidf))

tfidf Classification report: 
               precision    recall  f1-score   support

           0       0.41      0.61      0.49       803
           1       0.74      0.56      0.64      1597

    accuracy                           0.58      2400
   macro avg       0.58      0.59      0.57      2400
weighted avg       0.63      0.58      0.59      2400

