In [1]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [2]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

vec_king = wv['king']

In [3]:
vec_king.shape

(300,)

In [4]:
import pandas as pd
messages = pd.read_csv(r'D:\Machine learning\ML Programs\NLP\SpamClassifier\smsspamcollection\SMSSpamCollection.csv', sep='\t',names=['label','message'])
messages

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will ü b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [5]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [6]:
import re
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    
    review = [lemmatizer.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [7]:
[[i,j,k] for i,j,k in zip(list(map(len,corpus)),corpus, messages['message']) if i<1]

[[0, '', '645'], [0, '', ':) '], [0, '', ':-) :-)']]

In [8]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [118]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [120]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for sent in sent_token:
        words.append(simple_preprocess(sent))

words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [122]:
import gensim

In [124]:
##lets train word2vec from scrach
model = gensim.models.Word2Vec(words)

In [125]:
#to get all the vocabulary
#model.wv.index_to_key

In [128]:
model.corpus_count

5569

In [130]:
model.epochs

5

In [132]:
model.wv.similar_by_word('kid')

[('ask', 0.9971358180046082),
 ('stuff', 0.9970425367355347),
 ('out', 0.9969190955162048),
 ('doe', 0.9968945980072021),
 ('haha', 0.9968720078468323),
 ('went', 0.9968569278717041),
 ('eat', 0.9968563914299011),
 ('wat', 0.9968339800834656),
 ('meet', 0.9968189597129822),
 ('oso', 0.9968119263648987)]

In [134]:
model.wv['good'].shape

(100,)

In [136]:
import numpy as np
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
                #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [138]:
from tqdm import tqdm

In [140]:
#apply for the entire sentences
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  8%|██████                                                                       | 434/5569 [00:00<00:01, 4339.94it/s]D:\Anaconda\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
D:\Anaconda\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|████████████████████████████████████████████████████████████████████████████| 5569/5569 [00:00<00:00, 5602.64it/s]


In [142]:
len(X)

5569

In [144]:
X[0]

array([-0.16808623,  0.23723473,  0.12431974,  0.08470128,  0.09756371,
       -0.4965015 ,  0.16830523,  0.4663477 , -0.2754499 , -0.11563585,
       -0.15908201, -0.34014744, -0.0416117 ,  0.11570499,  0.19181043,
       -0.15184784,  0.13904537, -0.30804235, -0.07294898, -0.5033957 ,
        0.19881624,  0.11355119,  0.0890775 , -0.22258918, -0.02495692,
       -0.01223204, -0.22252996, -0.18638292, -0.25110924,  0.03999735,
        0.2992894 ,  0.00730077,  0.08395572, -0.17518467, -0.12368042,
        0.40124896,  0.05091217, -0.1484242 , -0.11222673, -0.47285596,
        0.11056571, -0.25400066, -0.1647861 ,  0.01966916,  0.1488185 ,
        0.0176622 , -0.11715864, -0.03399112,  0.20948389,  0.1390265 ,
        0.18460068, -0.18996044, -0.08201073,  0.04706401, -0.07213174,
        0.04136057,  0.15270828,  0.03004157, -0.3642294 ,  0.18650223,
       -0.00891278,  0.13524202, -0.00275848, -0.10514083, -0.29506224,
        0.29302412,  0.08009784,  0.22744654, -0.3458754 ,  0.39

In [146]:
##Independent feature
##X_new=np.array(X)
X_new = np.array(X, dtype=object)

In [148]:
X_new.shape

(5569,)

In [150]:
##dependent features
y = messages[list(map(lambda x: len(x)>0 , corpus))]
y = pd.get_dummies(y['label'])
y = y.iloc[:,0].values

In [154]:
y = y.astype(int)
y

array([1, 1, 0, ..., 1, 1, 1])

In [156]:
y.shape

(5569,)

In [158]:
for i, x in enumerate(X):
    print(f"Index {i}: shape {np.array(x).shape}")

Index 0: shape (100,)
Index 1: shape (100,)
Index 2: shape (100,)
Index 3: shape (100,)
Index 4: shape (100,)
Index 5: shape (100,)
Index 6: shape (100,)
Index 7: shape (100,)
Index 8: shape (100,)
Index 9: shape (100,)
Index 10: shape (100,)
Index 11: shape (100,)
Index 12: shape (100,)
Index 13: shape (100,)
Index 14: shape (100,)
Index 15: shape (100,)
Index 16: shape (100,)
Index 17: shape (100,)
Index 18: shape (100,)
Index 19: shape (100,)
Index 20: shape (100,)
Index 21: shape (100,)
Index 22: shape (100,)
Index 23: shape (100,)
Index 24: shape (100,)
Index 25: shape (100,)
Index 26: shape (100,)
Index 27: shape (100,)
Index 28: shape (100,)
Index 29: shape (100,)
Index 30: shape (100,)
Index 31: shape (100,)
Index 32: shape (100,)
Index 33: shape (100,)
Index 34: shape (100,)
Index 35: shape (100,)
Index 36: shape (100,)
Index 37: shape (100,)
Index 38: shape (100,)
Index 39: shape (100,)
Index 40: shape (100,)
Index 41: shape (100,)
Index 42: shape (100,)
Index 43: shape (100,

In [160]:
## this is the final independent features
# df=pd.DataFrame()
# for i in range(0,len(X)):
#     df=df.append(pd.DataFrame(X[i].reshape(1,-1)),ignore_index=True)

# rows = [x.reshape(1, -1) for x in X]
# df = pd.DataFrame(np.vstack(rows))

# X_clean = [x for x in X if np.array(x).shape == (100,)]
# df = pd.DataFrame(np.vstack(X_clean))

In [162]:
fixed_length = 100
X_fixed = []

for i, x in enumerate(X):
    x = np.array(x).flatten()
    if len(x) < fixed_length:
        # Pad with zeros at the end
        x = np.pad(x, (0, fixed_length - len(x)), mode='constant')
    elif len(x) > fixed_length:
        # Trim extra values
        x = x[:fixed_length]
    X_fixed.append(x)

In [164]:
rows = [x.reshape(1, -1) for x in X_fixed]
df = pd.DataFrame(np.vstack(rows))

In [166]:
df.shape

(5569, 100)

In [168]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.168086,0.237235,0.124320,0.084701,0.097564,-0.496502,0.168305,0.466348,-0.275450,-0.115636,...,0.361358,0.147492,0.016010,0.040547,0.416988,0.176173,0.149651,-0.197574,0.146932,-0.004424
1,-0.157158,0.212889,0.107652,0.073962,0.088060,-0.438548,0.138958,0.416169,-0.241294,-0.097067,...,0.323181,0.123781,0.009252,0.030100,0.358278,0.149132,0.132442,-0.181256,0.133731,-0.010982
2,-0.182129,0.255057,0.134364,0.098207,0.092645,-0.534734,0.167066,0.464374,-0.291990,-0.145462,...,0.354069,0.145737,0.009087,0.019074,0.430688,0.174047,0.097025,-0.232790,0.170839,0.015398
3,-0.234938,0.321891,0.162226,0.119405,0.128587,-0.676902,0.222630,0.640392,-0.377494,-0.148909,...,0.495875,0.197133,0.017867,0.062225,0.553872,0.238906,0.219897,-0.270563,0.199128,-0.015783
4,-0.209019,0.269090,0.143865,0.099015,0.117574,-0.578024,0.188027,0.552503,-0.327517,-0.133294,...,0.429215,0.169729,0.020814,0.055470,0.477486,0.211305,0.183209,-0.244473,0.167241,-0.013581


In [170]:
##Independent feature
X = df

In [172]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [174]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
2604,-0.227067,0.309265,0.164038,0.112151,0.126525,-0.649563,0.209865,0.608652,-0.364781,-0.158510,...,0.473501,0.188024,0.017868,0.049325,0.531986,0.227108,0.181289,-0.266798,0.186694,-0.007447
99,-0.161890,0.211842,0.115322,0.064273,0.095227,-0.456271,0.145730,0.427832,-0.247998,-0.111557,...,0.332782,0.132096,0.016501,0.036376,0.381714,0.169843,0.140439,-0.185549,0.141377,-0.007245
4309,-0.208532,0.292006,0.156011,0.106905,0.115860,-0.608542,0.197921,0.563156,-0.338962,-0.150031,...,0.440525,0.178377,0.018981,0.042833,0.504222,0.212712,0.153878,-0.253578,0.180295,0.000443
2005,-0.210726,0.266733,0.138659,0.091778,0.118159,-0.572883,0.191214,0.555779,-0.322358,-0.133267,...,0.436540,0.173245,0.022655,0.055657,0.478494,0.219638,0.196152,-0.234848,0.155758,-0.016641
1838,-0.188101,0.277192,0.150039,0.102703,0.104659,-0.572987,0.185624,0.510399,-0.315945,-0.148515,...,0.395289,0.160715,0.012008,0.025744,0.466648,0.186289,0.125955,-0.237284,0.177478,0.007984


In [176]:
y_train

array([1, 1, 0, ..., 1, 1, 1])

In [178]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()

In [180]:
classifier.fit(X_train, y_train)

RandomForestClassifier()

In [182]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 1, 0, ..., 1, 1, 1])

In [186]:
from sklearn.metrics import accuracy_score, classification_report
print("accuracy =>", accuracy_score(y_test, y_pred) * 100 , "%")
print('classification report :\n ', classification_report(y_test, y_pred))

accuracy => 97.48653500897666 %
classification report :
                precision    recall  f1-score   support

           0       0.89      0.90      0.90       133
           1       0.99      0.98      0.99       981

    accuracy                           0.97      1114
   macro avg       0.94      0.94      0.94      1114
weighted avg       0.98      0.97      0.97      1114

